services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      docmost-db:
        condition: service_healthy
      docmost-redis:
        condition: service_healthy
    environment:
      APP_URL: '${DOCMOST_DOMAIN}'
      APP_SECRET: '${DOCMOST_SECRET}'
      DATABASE_URL: 'postgresql://${DOCMOST_DB_USER}:${DOCMOST_DB_PASSWORD}@docmost-db:5432/${DOCMOST_DB_NAME}?schema=public'
      REDIS_URL: 'redis://docmost-redis:6379'
    expose:
      - '3000'
    restart: unless-stopped
    volumes:
      - type: volume
        source: docmost-data
        target: /app/data/storage
    networks:
      - docmost
      - nginx-external

  docmost-db:
    image: postgres:16-alpine
    container_name: docmost-db
    environment:
      POSTGRES_DB: ${DOCMOST_DB_NAME}
      POSTGRES_USER: ${DOCMOST_DB_USER}
      POSTGRES_PASSWORD: ${DOCMOST_DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - type: volume
        source: docmost-db-data
        target: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DOCMOST_DB_NAME}", "-U", "${DOCMOST_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - docmost
    expose:
      - '5432'

  docmost-redis:
    image: redis:7.2-alpine
    container_name: docmost-redis
    restart: unless-stopped
    volumes:
      - type: volume
        source: docmost-redis-data
        target: /data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - docmost
    expose:
      - '6379'

volumes:
  docmost-data:
    name: ${COMMON_NAME}_docmost-data
  docmost-db-data:
    name: ${COMMON_NAME}_docmost-db-data
  docmost-redis-data:
    name: ${COMMON_NAME}_docmost-redis-data

networks:
  docmost:
  nginx-external:
    external: true
    name: ${COMMON_NAME}_nginx-network