version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./nginx/setup/conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: web-root
        target: /var/www/certbot
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt
      - type: volume
        source: web-root
        target: /var/www/certbot

  php-config:
    image: alpine:latest
    container_name: php-config
    volumes:
      - type: bind
        source: ./php/config.php
        target: /source/config.php
      - type: volume
        source: cloud-data
        target: /data
    command: > 
      sh -c "cp /source/config.php /data/config.php"
      
  backup:
    image: backup
    container_name: backup
    build:
      context: ./backup
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: /data
        target: /tmp/source
      - type: volume
        source: api-volume
        target: /tmp/dist
      - type: bind
        source: $PROJECT_TEMP/backup
        target: /tmp/back

volumes:
  cloud-data:
    driver: local
  certbot-etc:
    driver: local
  certbot-var:
    driver: local
  web-root:
    driver: local