version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - cloud_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - cloud_network

  cloud:
    image: nextcloud:latest
    container_name: cloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: cloud-data
        target: /var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - cloud_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/prod/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/prod/conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: web-root
        target: /var/www/certbot
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt
    depends_on:
      - cloud
    networks:
      - cloud_network

networks:
  cloud_network:

volumes:
  db-data:
    driver: local
  cloud-data:
    driver: local
  web-root:
    driver: local
  certbot-etc:
    driver: local
  certbot-var:
    driver: local
