version: "3.8"

name: cloud

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - nginx-network
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: ./nginx/prod/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/prod/conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: web-root
        target: /var/www/certbot
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt
    depends_on:
      office:
        condition: service_started
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge

volumes:
  web-root:
    driver: local
  certbot-etc:
    driver: local
  certbot-var:
    driver: local