services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - nginx-network
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: ./nginx/prod/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/prod/conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: web-root
        target: /var/www/certbot
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge

volumes:
  web-root:
    driver: local
    name: cloud_web-root
  certbot-etc:
    driver: local
    name: cloud_certbot-etc
  certbot-var:
    driver: local
    name: cloud_certbot-var