services:
  nginx-setup:
    image: nginx:latest
    container_name: nginx-setup
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./nginx/setup/conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: web-root
        target: /var/www/certbot
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt
      - type: volume
        source: web-root
        target: /var/www/certbot

  backup:
    image: backup
    container_name: backup
    build:
      context: ./backup
      dockerfile: ./Dockerfile

volumes:
  certbot-etc:
    driver: local
    name: ${COMMON_NAME}_certbot-etc
  certbot-var:
    driver: local
    name: ${COMMON_NAME}_certbot-var
  web-root:
    driver: local
    name: ${COMMON_NAME}_web-root