version: '3.8'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_URL: '${DOCMOST_DOMAIN}'
      APP_SECRET: '${DOCMOST_SECRET}'
      DATABASE_URL: 'postgresql://${DOCMOST_DB_USER}:${DOCMOST_DB_PASSWORD}@db:5432/${DOCMOST_DB_NAME}?schema=public'
      REDIS_URL: 'redis://redis:6379'
    expose:
      - '3000'
    restart: unless-stopped
    volumes:
      - type: volume
        source: docmost-data
        target: /app/data/storage
    networks:
      - docmost
      - nginx-external

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DOCMOST_DB_NAME}
      POSTGRES_USER: ${DOCMOST_DB_USER}
      POSTGRES_PASSWORD: ${DOCMOST_DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - type: volume
        source: docmost-db-data
        target: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DOCMOST_DB_NAME}", "-U", "${DOCMOST_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - docmost
    expose:
      - '5432'

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: docmost-redis-data
        target: /data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - docmost
    expose:
      - '6379'

volumes:
  docmost-data:
    driver: local
  docmost-db-data:
    driver: local
  docmost-redis-data:
    driver: local

networks:
  docmost:
  nginx-external:
    external: true
    name: cloud_nginx-network