x-environment:
  &default-back-environment
  # These environment variables will be used by taiga-back and taiga-async.
  # Database settings
  POSTGRES_DB: "taiga"
  POSTGRES_USER: "${TAIGA_POSTGRES_USER}"
  POSTGRES_PASSWORD: "${TAIGA_POSTGRES_PASSWORD}"
  POSTGRES_HOST: "taiga-db"
  # Taiga settings
  TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
  TAIGA_SITES_SCHEME: "${TAIGA_SCHEME}"
  TAIGA_SITES_DOMAIN: "${TAIGA_DOMAIN}"
  TAIGA_SUBPATH: "${TAIGA_SUBPATH}"
  # Email settings.
  EMAIL_BACKEND: "django.core.mail.backends.${TAIGA_EMAIL_BACKEND}.EmailBackend"
  DEFAULT_FROM_EMAIL: "${TAIGA_EMAIL_DEFAULT_FROM}"
  EMAIL_USE_TLS: "${TAIGA_EMAIL_USE_TLS}"
  EMAIL_USE_SSL: "${TAIGA_EMAIL_USE_SSL}"
  EMAIL_HOST: "${TAIGA_EMAIL_HOST}"
  EMAIL_PORT: "${TAIGA_EMAIL_PORT}"
  EMAIL_HOST_USER: "${TAIGA_EMAIL_HOST_USER}"
  EMAIL_HOST_PASSWORD: "${TAIGA_EMAIL_HOST_PASSWORD}"
  # Rabbitmq settings
  RABBITMQ_USER: "${TAIGA_RABBITMQ_USER}"
  RABBITMQ_PASS: "${TAIGA_RABBITMQ_PASS}"
  # Telemetry settings
  ENABLE_TELEMETRY: "${TAIGA_ENABLE_TELEMETRY}"

  PUBLIC_REGISTER_ENABLED: "${TAIGA_PUBLIC_REGISTER_ENABLED}"
  ENABLE_GITHUB_AUTH: "${TAIGA_ENABLE_GITHUB_AUTH}"
  GITHUB_API_CLIENT_ID: "${TAIGA_GITHUB_API_CLIENT_ID}"
  GITHUB_API_CLIENT_SECRET: "${TAIGA_GITHUB_API_CLIENT_SECRET}"

x-volumes:
  &default-back-volumes
  # These volumens will be used by taiga-back and taiga-async.
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media

services:
  taiga-db:
    container_name: taiga-db
    image: postgres:12.3
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "${TAIGA_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${TAIGA_POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TAIGA_POSTGRES_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    container_name: taiga-back
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
      - nginx-external
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async:
    container_name: taiga-async
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async-rabbitmq:
    container_name: taiga-async-rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${TAIGA_RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${TAIGA_RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${TAIGA_RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${TAIGA_RABBITMQ_VHOST}"
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    container_name: taiga-front
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "${TAIGA_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "${TAIGA_WEBSOCKETS_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_SUBPATH: "${TAIGA_SUBPATH}"
      ENABLE_GITHUB_AUTH: "true"
      GITHUB_CLIENT_ID: "${TAIGA_GITHUB_API_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${TAIGA_GITHUB_API_CLIENT_SECRET}"
      PUBLIC_REGISTER_ENABLED: "true"
    networks:
      - taiga
      - nginx-external

  taiga-events:
    container_name: taiga-events
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: "${TAIGA_RABBITMQ_USER}"
      RABBITMQ_PASS: "${TAIGA_RABBITMQ_PASS}"
      TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
    networks:
      - taiga
      - nginx-external
    depends_on:
      taiga-events-rabbitmq:
        condition: service_started

  taiga-events-rabbitmq:
    container_name: taiga-events-rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${TAIGA_RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${TAIGA_RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${TAIGA_RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${TAIGA_RABBITMQ_VHOST}"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    container_name: taiga-protected
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "${TAIGA_ATTACHMENTS_MAX_AGE}"
      SECRET_KEY: "${TAIGA_SECRET_KEY}"
    networks:
      - taiga
      - nginx-external

volumes:
  taiga-static-data:
    name: cloud_taiga-static-data
  taiga-media-data:
    name: cloud_taiga-media-data
  taiga-db-data:
    name: cloud_taiga-db-data
  taiga-async-rabbitmq-data:
    name: cloud_taiga-async-rabbitmq-data
  taiga-events-rabbitmq-data:
    name: cloud_taiga-events-rabbitmq-data

networks:
  taiga:
  nginx-external:
    external: true
    name: cloud_nginx-network
