server {
    listen 80;
    listen [::]:80;

    server_name duvanoff.su www.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name cloud.duvanoff.su www.cloud.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name office.duvanoff.su www.office.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name track.duvanoff.su www.track.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name taiga.duvanoff.su www.taiga.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name doc.duvanoff.su www.doc.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name out.doc.duvanoff.su www.out.doc.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}
