server {
    listen 80;
    listen [::]:80;

    server_name duvanoff.su www.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name cloud.duvanoff.su www.cloud.duvanoff.su;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}