server {
    listen 80;
    listen [::]:80;

    server_name duvanoff.su www.duvanoff.su;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name duvanoff.su www.duvanoff.su;

    charset utf-8;
    access_log off;

    ssl_certificate /etc/letsencrypt/live/duvanoff.su/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/duvanoff.su/privkey.pem;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    keepalive_timeout 70;

    location / {
        root /var/www/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }
}